n1=input("enter first number:")
n2=input("enter second number:")
sum=float(n1)+float(n2)
sub=float(n1)-float(n2)
mul=float(n1)*float(n2)
div=float(n1)/float(n2)
mod=float(n1)%float(n2)
print("sum of {0} and {1} is {2}".format(n1,n2,sum))
print("subraction of {0} and {1} is {2}".format(n1,n2,min))
print("multiplication of {0} and {1} is {2}".format(n1,n2,mul))
print("division of {0} and {1} is {2}".format(n1,n2,div))
print("modulus of {0} and {1} is {2}".format(n1,n2,mod))
